name: linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.30'
          - '5.34'
          - '5.36'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v4
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        run: |
          cpanm -n -q Alien::LibJQ Module::Build
          perl ./Build.PL
          ./Build installdeps --cpan_client 'cpanm -n -q'
      - name: Run tests
        run:  ./Build test verbose=1
